src/Controllers/CopyPatrol.php, src/Dao/EnwikiDao.php
From my testing, this improves load time dramatically. Everything but querying for WikiProjects is done en masse. The biggest slowdown was the API, so checking for dead links in only three different requests makes a big difference, it seems.
This PR I'm not super confident in, but it works :) I know I need to use prepared statements in `getRevisionDetailsMulti`, but I could not get it to work for some reason. Meanwhile `handleGet` looks very messy, but this sequence of loops is necessary to ensure we have all the data we need before updating the view – and doing so in a way that is performant.
=> Make batch requests/queries to API and database to improve performance

public_html/templates/index.html, src/Controllers/CopyPatrol.php, src/Dao/PlagiabotDao.php
Some refactoring of CopyPatrol class
=> Automatically mark deleted pages as reviewed

src/Dao/PlagiabotDao.php
=> Show only records after June 20, 2016

src/Dao/PlagiabotDao.php
Context: https://phabricator.wikimedia.org/T145436#2733046
I'm going to update MusikBot and the wikiprojects table to not include `WikiProject_` in the names, meaning we no longer need this bit of code.
Also, MusikBot ignores sub-WikiProjects (e.g. "Wikipedia:WikiProject Alternative music/The Smashing Pumpkins"), so that code here can also be removed.
=> Remove code assuming values in wikiprojects table are prefixed with WikiProject_

.env_example, .gitignore, README.md, composer.json, composer.lock, src/App.php, src/Controllers/CopyPatrol.php
This change adds a PSR-6 compatible caching system, instead of
only using Redis. This makes it easier to run locally (without
installing Redis).
Also extends the local-development setup instructions, making it
clearer what needs to be done to get things
up and running. Composer will now create a default .env file.
The Less cache is moved to the top-level 'cache' directory, because
this is where the cache is when Redis isn't used and because /src
seems like an odd place for volatile files. The new cache directory is added to the repo (empty) and a note about making it writable added to the readme.
The /login route is removed because it wasn't used anyway.
`composer.lock` is added, because then `composer install` will install the same thing for everyone, and the same in production (where …
=> Generalised caching, more documentation, and other set-up things

public_html/js/index.js
This collapses the current record's two compare panels if either
of them is still open when the user clicks 'page fixed' or 'no
action needed'.
Bug: https://phabricator.wikimedia.org/T141820
=> Close any open 'compare' panels after buttons have been clicked

src/App.php
It was redirecting to the 'home' URL, which requires the language
parameter.
Bug: https://phabricator.wikimedia.org/T150919
=> Redirect to the root URL on logout

public_html/templates/leaderboard.html, src/App.php, src/Controllers/Leaderboard.php
This updates the Leaderboard controller to follow the same pattern
as the other controllers and inherit from CopyPatrol. This makes
it simpler to retrieve the current wiki langugage in the same way
that it's done elsewhere (and so is hopefully less confusing).
Some of the Twig variable usages were also simplified to the dot
syntax rather than the array syntax.
Bug: https://phabricator.wikimedia.org/T150928
=> Fix Leaderboard language-specific links

public_html/templates/header.html, src/App.php, src/Less/index.less
This changes to using the Bootstrap navbar for the main menu, so
that it's easier to incorporate a dropdown with which to switch
from English to French or vice versa. This switch will to to the
corresponding other-language page (so if you're on the leaderboard
and switch you'll be on the other language's leaderboard).
Bug: https://phabricator.wikimedia.org/T150956
=> Add a dropdown for switching between Wikipedias

composer.lock, public_html/templates/base.html, public_html/templates/index.html, src/Controllers/CopyPatrol.php, src/Dao/PlagiabotDao.php, src/Dao/WikiDao.php
This change hides the WikiProject search field if there
are no WikiProjects in the database for the Wikipedia language
in use.
Half of T152173 is fixed as well, because it's easier to test
this new functionality against a language (pt) that doesn't
have WikiProjects.
Composer is also updated, just for fun.
Bug: https://phabricator.wikimedia.org/T152134
Bug: https://phabricator.wikimedia.org/T152173
=> Only show the WikiProject search field when required

src/App.php
Rather than have displayErrorDetails hard-coded to true.
=> Set error output based on log level

src/Dao/PlagiabotDao.php
When searchCriteria == 'page_exact', only the records
for this exact page will be returned unlike 'page' that
does a SQL like '%text%' comparison.
This will be used by PageTriage to link to CopyPatrol
results for a specific page.
Bug: https://phabricator.wikimedia.org/T201075
=> Allow searching for a page with the exact title

src/Dao/PlagiabotDao.php
Apparently they don't work and cause errors.
=> PlagiabotDao: Don't try to use typed prepared params

src/Controllers/CopyPatrol.php, src/Dao/PlagiabotDao.php
This change allows one to pass in a `revision=:revId` parameter in the query
string. If present, we'll attempt to load results for that revision ID and will
merge them in with any other records found from the search.
Bug: T207345
=> Incorporate revision id search

composer.json, src/App.php
Apparently this isn't needed anymore, and it's actually breaking the
'home' route from redirecting to the page with the language code (e.g.
if your browser is set to English, it should redirect to /en)
Also add ext-json requirement to composer.json
=> Remove trailing slash middleware

src/App.php, src/Dao/PlagiabotDao.php
This is to monitor if EranBot is working properly. We'll use UptimeRobot
to continually ping the /activity_check endpoint, which will emaul us if
there is an unsuccessful response.
Bug: T262767
=> Add endpoint to check if there's recent activity

public_html/i18n/en.json, public_html/i18n/qqq.json
Add `simple-wikipedia` entries to i18n per step 3 from _README (Adding a new language)_, though I'm not entirely sure it's needed...
Bug: [T318032](https://phabricator.wikimedia.org/T318032)
=> i18n: Add simple english

.github/workflows/ci.yml, .travis.yml, README.md
Builds on `travis-ci.org` ended back in June 2021. This means Travis has not been providing builds for this repo since then. True enough, the last build on Travis seems to be from [two years ago](https://travis-ci.org/wikimedia/CopyPatrol). Switching to GitHub Actions has been the course of action for pywikibot, and GitHub Actions supports an unlimited amount of free minutes for public projects, so this is a switch to GitHub Actions to get continuous integration back up.
From https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions:
> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners.
This commit introduces one dependency: …
=> Migrate from Travis to GitHub Actions

.github/workflows/ci.yml, README.md, composer.json, composer.lock, public_html/templates/base.html, src/App.php
Routes ending in .css or other common MIME types don't get loaded. There's probably a way to fix this for everyone, but simply not using .css as the extension will force it to work.
Other changes:
* Bump to PHP 7.4
* Use wikimedia/less.php, as oyejorge/less.php is abandoned
* Add ext-intl as a dependency in composer.json
Bug: [T332078](https://phabricator.wikimedia.org/T332078)
Bug: [T331220](https://phabricator.wikimedia.org/T331220)
=> Rename the CSS route 'styles' so that it loads natively on local envs

.env_example, .github/workflows/ci.yml, Dockerfile, README.md, docker-compose.dev.yml
This commit adds a Dockerfile for building a reproducible image of CopyPatrol based on Toolforge PHP 7.4 images. The Dockerfile mostly emulates the Toolforge environment, with slight modifications in development mode to make development easier (such as enabling XDebug in development mode).
The `docker-compose.dev.yml` file ensures that CopyPatrol is started with additional services, such as Redis, and mounts, such as the main program mount on the public user directory. It also ensures that port 9000/9003 are made accessible within the container to allow remote XDebug step debugging.
Note that the Docker Compose file binds to port 80 for the webserver. As the Twig templates are written now, ports are not properly handled when linking to server resources.
This adds the following checks:
* …
=> Add Dockerfile, development docker-compose

src/Controller/ApiController.php
Currently, the parameter names for the feed filtering API do not correspond to the parameters accepted by the API giving the appearance that the API is broken. For example, [the docs](http://copypatrol.wmcloud.org/api) give me the following command to filter for a specific page:
```sh
curl -X 'GET' \
'https://copypatrol.wmcloud.org/api/feed/en?filter=all&filter_page=List%20of%20foreign%20recipients%20of%20the%20L%C3%A9gion%20d%27Honneur%20by%20country' \
-H 'accept: application/json'
```
However, when the command is run, the default list of pages is returned and no filtering occurs. The correct command would have been
```sh
curl -X 'GET' \
'https://copypatrol.wmcloud.org/api/feed/en?filter=all&filterPage=List%20of%20foreign%20recipients%20of%20the%20L%C3%A9gion%20d%27Honneur%20by%20country …
```
=> Correct parameter name in docs
