wikimedia/CopyPatrol

- src/Controllers/CopyPatrol.php
- src/Dao/PlagiabotDao.php
> Show 'all reviewed cases' instead of fixed or no action

- .gitignore
- public_html/js/index.js
- src/App.php
> Trim trailing slash from routes, if present

- public_html/templates/base.html
- src/Controllers/CopyPatrol.php
- src/Dao/PlagiabotDao.php
- src/Less/index.less
> Add option to show only edits in the Draft namespace

- public_html/templates/base.html
- public_html/templates/index.html
- src/Controllers/CopyPatrol.php
I have tested functions I added but I couldn't test it in local app. 
Bug: T139009
> Add ORES scores

- src/Controllers/CopyPatrol.php
- src/Dao/EnwikiDao.php
> Filter out users in user whitelist, caching the whitelist in Redis

- composer.lock
`composer.json` was updated without `composer update` being run. This fixes it and also brings all package updates in.
> Bring composer.lock up to date

- public_html/js/index.js
- src/App.php
- src/Controllers/CopyPatrol.php
- src/Dao/WikiDao.php
This commit:
* Removes Redis in favor of API call to get whitelist
* Handle error when whitelist page is empty
> Get user whitelist to work again

- src/App.php
Before, if an invalid language was requested (but one that still
passed the wikiLang regex, e.g. qq) the app would use it regardless.
This change adds a new middleware function that checks the incoming
language against the list of supported languages, and throws a 404
if it doesn't match.
Bug: https://phabricator.wikimedia.org/T152134
> Validate the wiki language in the route

- public_html/i18n/en.json
- public_html/i18n/qqq.json
- public_html/js/index.js
- public_html/templates/base.html
- public_html/templates/index.html
- src/Controllers/CopyPatrol.php
- src/Dao/PlagiabotDao.php
- src/Less/index.less
Bug: https://phabricator.wikimedia.org/T154811
This also fixes a bug where the WikiProject bubble links weren't functional on records shown with "Load more".
If you attempt to open a permalink to a record that is for a different project than what the cookie is set to, you are redirected and the cookie is changed.
> Add ability to link to a specific record via permalink

- public_html/i18n/en.json
- public_html/i18n/qqq.json
- public_html/js/index.js
- public_html/templates/blocked.html
- src/App.php
- src/Controllers/CopyPatrol.php
- src/Dao/WikiDao.php
Bug: https://phabricator.wikimedia.org/T178681
> Prevent blocked users from doing reviews

- public_html/templates/base.html
Bug: https://phabricator.wikimedia.org/T204369
> Add noindex rule in page header

- src/Dao/PlagiabotDao.php
Don't rely on callers to escape/sanitize things.
Bug: T208280
> SECURITY: Use prepared parameters consistently

- src/App.php
> Fix error on undefined index for HTTP_ACCEPT_LANGUAGE

- src/Dao/WikiDao.php
> Actor table migration

- .env_example
- src/Dao/WikiDao.php
> WikiDao: update to use new replicas

- .env_example
- composer.json
- composer.lock
- public_html/templates/index.html
- src/App.php
- src/Controllers/CopyPatrol.php
- src/Controllers/Ithenticate.php
This means we no longer rely on an outside webserver to fetch document
IDs from Ithenticate.
Bug: T309816
> Migrate earnbot's ithenticate script to CopyPatrol

- public_html/i18n/en.json
- public_html/i18n/qqq.json
- public_html/js/index.js
- public_html/templates/base.html
- public_html/templates/leaderboard.html
- src/Controllers/CopyPatrol.php
- src/Less/index.less
**Note:** CI builds currently failing due to [T331220](https://phabricator.wikimedia.org/T331220).
This aims to fulfill a requested feature to search through reviews done by someone else.
* Searching by "reviewed cases" now shows a box for filtering by reviewer.
* The `filterUser` parameter can now be used to filter users.
* The leaderboard now includes a link to the user's reviews.
* Added an i18n message and its respective `qqq` entry.
* Converted the search area to CSS grid to make the new input look good.
Bug: [T331219](https://phabricator.wikimedia.org/T331219)
> Add option to search reviews by user

- .env_example
As noted in https://github.com/wikimedia/CopyPatrol/pull/159#issuecomment-1473811271
> Change `;` comment notation in `.env_example` to `#` notation

- composer.json
- i18n/en.json
- i18n/qqq.json
- src/Controller/AppController.php
- src/Model/Record.php
- src/Repository/WikiRepository.php
- templates/feed.html.twig
- tests/Model/RecordTest.php
These are very slow to fetch and our users have informed us they don't really use the scores anyway. See https://w.wiki/7tWk
> Remove damage scores

- src/Model/Record.php
- tests/Model/RecordTest.php
Adds a `$includeExternalLinks` option to `parseWikitext` which enables parsing masked external links (`[https://w.wiki/M like this]`). This fixes tags showing up as raw wikitext (with a clickable link) instead of a properly-displaying tag. Edit summaries don't have this functionality, matching the behavior of MediaWiki.
This PR also adds additional tests and `rel="nofollow"` to external links.
n.b. This will make the function deviate from its [XTools implementation](https://github.com/x-tools/xtools/blob/4795fb88dd392bb0474219be3ef9a1fc019a228b/src/Model/Edit.php#L336). It might be good to change the code there as well.
Bug: [T372531](https://phabricator.wikimedia.org/T372531)
> Process masked external links in tag wikitext
